### ISSUE TITLE
Project maintainer wanted

### ISSUE THREAD

**Issue by axic** [ethereum/dopple#1]
Currently there is a duplicate version of this in the aleth tree.

How about maintaing it here and putting it as a "git subtree" into aleth?

**Comment by chfast** [comment]
I don't have time to maintain this.

**Comment by pipermerriam** [comment]
At some point in the near-ish (3-6 months?) my team will likely start using this and thus will likely take ownership of maintaining it.

**Comment by axic** [comment]
I have replayed the updates to it from Aleth: https://github.com/ethereum/dopple/tree/update

It should be a good base to take it over from.

**Comment by axic** [comment]
Merged everything to `master`, it is up for taking now 😉

**Comment by Bhargavasomu** [comment]
@axic I have been developing on the `python ecosystem of ethereum` for the past 4.5 months. This project sounds interesting and worth maintaining. Do you mind if I could take up this task? I believe that this would make `JSON RPC testing` a lot easier too.

/cc @pipermerriam

**Comment by chfast** [comment]
Yes, this project was always intended to be used by other Python projects.

There is one detail that is important for Aleth - this script can be run without install step.

**Comment by Bhargavasomu** [comment]
@chfast so you mean to say that `Dopple` is currently being used by `Aleth`?

**Comment by chfast** [comment]
Yes, it's here (as git submodule): https://github.com/ethereum/dopple/tree/f7d67a385a2254192709b81604d12f89d36a5c04

Some time ago Aleth had a HTTP server for handling RPC request via HTTP. Long story short, we had problems with it. And we also aim for more modular architecture of Aleth (more independent processes, not only C++).

We replaced the HTTP server with this Python script to proxy HTTP requests to Unix Sockets or Windows Named Pipelines.

**Comment by pipermerriam** [comment]
cc @carver @cburgdorf @lithp @ralexstokes 

I have no idea what the state of this codebase is, but this might be an excellent candidate for us to 1) learn how to distribute python applications using homebrew and/or a PPA and 2) to expose HTTP based JSON-RPC API for trinity.

Looks like everything is in a single `dopple.py` module that's only ~300 lines long so we'd just need to wrap this up as a python package, do some small code organization and cleanup, write up a small test suite, and this could be good to go without much effort.

**Comment by ralexstokes** [comment]
without looking more closely at what all is entailed in fully maintaining this as a robust piece of infra we can rely on.... i do have a dash of experience setting up homebrew packages and would be open to taking a pass at that

**Comment by chfast** [comment]
Homebrew, PPA, etc are not really interesting distribution options for us. We prefer to distribute just an archive of executables. Then pip would be the second best option.

Any chance of optionally distributing this as a standalone Python bundle? I've seen cython can produce single binary out of Python package.

**Comment by pipermerriam** [comment]
@chfast yes, `pip` style install would be there too.  Would a wheel work for you?

Re-doing this in cython also sounds interesting since this doesn't have any dependencies.

**Comment by chfast** [comment]
Having no dependencies would be ideal, but I'm expecting some to be added in future (e.g. to add websocket support). Anyway, go ahead for proper Python packaging.

**Comment by cburgdorf** [comment]
As I'm setting up a DappNode package for Trinity, it starts hurting us that our JSON-RPC API isn't exposed via HTTP (e.g. hooking into the DappNode Dashboard relies on having the JSON-RPC API exposed via HTTP).

I'm going to open up a PR soon to turn this into a proper python package so that we can start using it in Trinity.
